save_dir: test_data/onnx_models
density_profile: additional_files/density_temp_height.json
query: "from(bucket: \"logicmelt\") |> range(start: -20d)        |> filter(fn: (r) => r[\"_measurement\"] == \"particle\")"
influxdb:
  url: http://localhost:8086
  token: logicmelt
  org: logicmelt
  columns_in: [""]
  columns_out: [""]
aggregator:
  type: "aggregated"
  time_resolution: 1 # seconds
train_params:
  n_jobs: -1
  scoring: ["r2", "neg_root_mean_squared_error"]
  cv: 5
  n_iter: 1
  refit: "neg_root_mean_squared_error"
  train_split: 0.8
  shuffle: false
model:
  KNeighborsRegressor:
    KNeighborsRegressor__n_neighbors: "Range(2, 21, 1)"
    KNeighborsRegressor__weights: ["uniform", "distance"]
    KNeighborsRegressor__algorithm: ["ball_tree", "kd_tree", "brute"]
    KNeighborsRegressor__leaf_size: "Range(5, 205, 5)"
    KNeighborsRegressor__metric: ["euclidean", "minkowski"]
    KNeighborsRegressor__p: [1, 2]
  SVR:
    SVR__C: "Range(1, 51, 1)"
    SVR__kernel: ["rbf", "sigmoid"]
    SVR__degree: "Range(0, 20, 1)"
    SVR__gamma: "Range(0, 3.1, 0.1)"
    SVR__coef0: "Range(0, 3.1, 0.1)"
  RandomForestRegressor:
    RandomForestRegressor__n_estimators: "Range(10, 100, 1)"
    RandomForestRegressor__max_depth: "Range(2, 10, 1)"
    RandomForestRegressor__max_features: ["sqrt", "log2", 11]
    RandomForestRegressor__criterion: [
      "squared_error",
      "friedman_mse",
      "absolute_error",
      "poisson"
    ]
    RandomForestRegressor__max_samples: [0.1, 0.2, 0.5]