# influxdb:
  # url: http://localhost:8086
  # token: logicmelt
  # org: logicmelt
  # columns_in: ["EventID", "process_ID", "phi[rad]", "theta[rad]", "density_day_idx"]
  #columns_out: ""
aggregator:
  type: "raw"
  time_resolution: 1 # seconds
train_params:
  n_jobs: -1
density_profile: additional_files/density_temp_height.json
