save_models: 
  type: HTTPServer
  url: http://localhost:4000/
  write_token: 'SEC'
  read_token: 'RET'
density_profile: additional_files/density_temp_height.json
logging:
  enabled: true
  console: true
  file: false
  logging_level: DEBUG
  log_output: ./data/logs/
query: "from(bucket: \"logicmelt\") |> range(start: -30d)        |> filter(fn: (r) => r[\"_measurement\"] == \"particle\")"
influxdb:
  url: http://localhost:8086
  token: logicmelt
  org: logicmelt
  columns_in: [""]
  columns_out: ["multiplicity"]
aggregator:
  type: "raw"
  time_resolution: 60 # seconds
train_params:
  n_jobs: -1
  scoring: ["r2", "neg_mean_squared_error"]
  cv: 5
  n_iter: 100
  refit: "neg_mean_squared_error"
  train_split: 0.8
  shuffle: true
model:
  SVR:
    SVR__C: "Range(1, 51, 1)"
    SVR__kernel: ["rbf", "sigmoid"]
    SVR__degree: "Range(0, 51, 1)"
    SVR__gamma: "Range(0, 3.1, 0.1)"
    SVR__coef0: "Range(0, 3.1, 0.1)"